Repository paust-team/paust-db, pull requests merged in 2019-02, with the labels that each got.

#99 Add paust-db logger for MasterApplication
  client/cmd/paust-db-client/commands/client.go
  libs/log/fmt_logger.go
  libs/log/logger.go
  master/MasterApplication.go
Labels: enhancement

#105 Add paust-db logger filter and change logging of master application
  client/httpclient_test.go
  cmd/paust-db/commands/master.go
  libs/db/c_rocks_db.go
  libs/db/c_rocks_db_batch_test.go
  libs/db/types.go
  libs/log/filter.go
  libs/log/filter_test.go
  libs/log/fmt_logger.go
  libs/log/fmt_logger_test.go
  libs/log/logger.go
  libs/log/logger_test.go
  master/MasterApplication.go
  master/MasterApplication_test.go
Labels: enhancement

#101 Add docker clustering feature and READ.md
  .gitignore
  Dockerfile
  docker/Makefile
  docker/README.md
  docker/docker-compose.yml
  docker/wrapper.sh
Labels: feature

#107 Update dependency version(golang, alpine, tendermint)
  Dockerfile
Labels: enhancement

#110 Change default directory of paust-db master application
  client/httpclient_test.go
  cmd/paust-db/commands/master.go
  master/MasterApplication.go
  master/MasterApplication_test.go
Labels: enhancement

#113 Change broadcast method of put function and add elapsed time printing of client CLI
  client/cmd/paust-db-client/commands/client.go
  client/httpclient.go
  client/httpclient_write_test.go
  client/interface.go
Labels: enhancement

#116 Add endpoint flag for client cli
  client/cmd/paust-db-client/commands/client.go
  consts/consts.go
Labels: enhancement

#118 Add status command for client cli
  client/cmd/paust-db-client/commands/client.go
Labels: enhancement

#119 Fix query time range bug
  client/httpclient.go
  client/httpclient_internal_test.go
  client/httpclient_read_test.go
  client/httpclient_test.go
  master/MasterApplication_test.go
  master/MasterApplication_unit_test.go
  types/types.go
  types/types_test.go
Labels: bug

#120 Delete useless function which was used only once
  master/MasterApplication.go
  types/types.go
  types/types_test.go
Labels: enhancement

#123 Change qualifier of client to string
  client/README.md
  client/cmd/paust-db-client/commands/client.go
  client/httpclient.go
  client/httpclient_internal_test.go
  client/httpclient_read_test.go
  client/httpclient_test.go
  client/httpclient_write_test.go
  client/interface.go
  client/types.go
  client/util/util_test.go
  test/write_directory/recursive_directory/test.json
  test/write_directory/test1.json
  test/write_directory/test2.json
  test/write_directory/test3.json
  test/write_file.json
Labels: enhancement
