Repository paust-team/paust-db, pull requests merged in 2019-03, with the labels that each got.

#126 Change query interface of client
  client/README.md
  client/cmd/paust-db-client/commands/client.go
  client/httpclient.go
  client/httpclient_read_test.go
  client/interface.go
  client/types.go
Labels: enhancement

#127 Add a script file for travis-ci
  .travis.yml
Labels: enhancement

#133 Add error handling of putting zero-value timestamp data and change data input type
  README.md
  client/README.md
  client/cmd/paust-db-client/commands/client.go
  client/httpclient.go
  client/types.go
Labels: bug, enhancement

#135 Fix client cli put command bug
  client/cmd/paust-db-client/commands/client.go
Labels: bug

#138 Change rowkey structure
  client/httpclient.go
  client/httpclient_internal_test.go
  client/httpclient_read_test.go
  client/types.go
  master/MasterApplication.go
  master/MasterApplication_test.go
  master/MasterApplication_unit_test.go
  types/types.go
  types/types_test.go
Labels: bug

#139 Add error handling when query start timestamp is greater than end
  client/httpclient.go
  master/MasterApplication.go
Labels: bug

#149 Indent query, fetch JSON response of client
  client/httpclient.go
Labels: enhancement

#151 Change requirement version of tendermint
  .travis.yml
  Dockerfile
  README.md
Labels: bug
